---
title: "Survey Data Analysis"
output: html_document
date: "2024-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# Load packages for data handling, visualization, and formatting
library(tidyverse)
library(here)
library(readxl)
library(stringr)
library(gt)
library(openxlsx)
library(survival)
library(survminer)
library(psych)
library(viridis)
library(ggtext)
library(gridExtra)
library(RColorBrewer)

# Source custom functions
source("functions.R")

# Set global options
options(stringsAsFactors = FALSE)
options(scipen = 100, digits = 4)


# Load reference data: country-to-region mapping
country_dict <- readxl::read_excel("data/countries_regions.xlsx")

# Define path to directory containing raw survey CSVs
directory_path <- "data"

# Identify all CSV files in the directory
csv_files <- list.files(path = directory_path, pattern = "\\.csv$")

# Load each CSV and store in a list of data frames
data_list <- lapply(csv_files, function(file) {
  read_csv(file.path(directory_path, file))
})

# Combine all individual survey CSVs into one data frame
df <- bind_rows(data_list)

df[df == ""] <- NA
df[df == "#N/A"] <- NA
df[df == "Other. Please specify:"] <- "Other"
df[df == "None"] <- NA

# Remove metadata rows (first two) from the combined data frame
df <- df[-c(1, 2), ]

df <- merge(df, country_dict, by.x = "Q8", by.y = "name", all.x = TRUE)

responses_n <- nrow(df)

#if Q1 was not answered, we can assume the person exited the survey without answering questions
drop_outs2 <- df %>% filter(is.na(Q1))
drop_outs_sum <- nrow(drop_outs2)

df <- df %>% filter(!is.na(Q1))
df <- df %>%
  filter(!is.na(df$StartDate))

```

```{r include=FALSE}
# Compute completion status for Metrics section (at least 2 responses)
sub_df_metrics <- df[,c(9,56:94)] 

filtered_df <- sub_df_metrics %>%
  mutate(metrics_section_answered = rowSums(!is.na(across(-ResponseId)))) %>%
  filter(metrics_section_answered >= 2) 

filtered_df$metrics_section_answered <- ifelse(filtered_df$metrics_section_answered > 0, 1, 0)

metrics_section <- filtered_df[,c("ResponseId", "metrics_section_answered")]

```

```{r include=FALSE}
# Compute completion status for Questions section (at least 2 responses)
sub_df_questions <- df[,c(9,95:160)]

filtered_df <- sub_df_questions %>%
  mutate(questions_section_answered = rowSums(!is.na(across(-ResponseId)))) %>%
  filter(questions_section_answered >= 2) 

filtered_df$questions_section_answered <- ifelse(filtered_df$questions_section_answered > 0, 1, 0)

questions_section <- filtered_df[,c("ResponseId", 
                                          "questions_section_answered")]
```

```{r include=FALSE}
# Compute completion status for Evaluation section (at least 2 responses)
sub_df_evaluation <- df[,c(9,161:164)]

filtered_df <- sub_df_evaluation %>%
  mutate(evaluation_section_answered = rowSums(!is.na(across(-ResponseId)))) %>%
  filter(evaluation_section_answered >= 2) 

filtered_df$evaluation_section_answered <- ifelse(filtered_df$evaluation_section_answered > 0, 1, 0)

evaluation_section <- filtered_df[,c("ResponseId", 
                                            "evaluation_section_answered")]
```

```{r include=FALSE}
#Confidence section
sub_df_confidence <- df[,c(9,165:174)]

filtered_df <- sub_df_confidence %>%
  mutate(confidence_section_answered = rowSums(!is.na(across(-ResponseId)))) %>%
  filter(confidence_section_answered >= 1) 

filtered_df$confidence_section_answered <- ifelse(filtered_df$confidence_section_answered > 0, 1, 0)

confidence_section <- filtered_df[,c("ResponseId", 
                                            "confidence_section_answered")]
```

```{r include=FALSE}
#Barriers section
sub_df_barriers <- df[,c(9,175:186)]

filtered_df <- sub_df_barriers %>%
  mutate(barriers_section_answered = rowSums(!is.na(across(-ResponseId)))) %>%
  filter(barriers_section_answered >= 2) 

filtered_df$barriers_section_answered <- ifelse(filtered_df$barriers_section_answered > 0, 1, 0)
barriers_section <- filtered_df[,c("ResponseId", 
                                        "barriers_section_answered")]


```

```{r include=FALSE}
df <- df %>%
  left_join(metrics_section, by = "ResponseId") %>%
  left_join(questions_section, by = "ResponseId") %>%
  left_join(evaluation_section, by = "ResponseId") %>%
  left_join(barriers_section, by = "ResponseId")%>%
  left_join(confidence_section, by = "ResponseId")

# anyone who has not contributed to any policy dialogues around COVID-19 are excluded here
dropout <- nrow(df[(df$Q2 == "No" & df$Q4 == "No"), ])
df <- df[!(df$Q2 == "No" & df$Q4 == "No"), ] 

# summarizing Q2 and Q4 (due to many levels in diagram) - either they engaged in policy dialogues themselves or their supervisor did (Q4)

df$Q3_national <- ifelse(!is.na(df$Q3_1) | 
                              !is.na(df$Q3_7) | 
                              !is.na(df$Q3_2) | 
                              !is.na(df$Q3_6) | 
                              !is.na(df$Q3_3) | 
                              !is.na(df$Q3_4) |
                              !is.na(df$Q5_1) |
                              !is.na(df$Q5_2) |
                              !is.na(df$Q5_7) |
                              !is.na(df$Q5_6) |
                              !is.na(df$Q5_4),1,NA )

df$Q3_sub_national <- ifelse(!is.na(df$Q3_5) | 
                              !is.na(df$Q3_8) | 
                              !is.na(df$Q3_10)|
                              !is.na(df$Q5_5) |
                              !is.na(df$Q5_8) |
                              !is.na(df$Q5_10),1,NA )

df$Q3_field <- ifelse(!is.na(df$Q3_11) | 
                              !is.na(df$Q3_12),1,NA )

df$Q3_other <- ifelse(!is.na(df$Q3_16) | 
                              !is.na(df$Q3_15),1,NA )

# remove columns after aggregation
columns_to_remove <- c("Q3_1", "Q3_7", "Q3_2", "Q3_6", "Q3_3", "Q3_4",
                       "Q5_1", "Q5_2", "Q5_7", "Q5_6", "Q5_4",
                       "Q3_5", "Q3_8", "Q3_10", "Q5_5", "Q5_8", "Q5_10",
                       "Q3_11", "Q3_12","UserLanguage", "DistributionChannel",
                       "Q0","Status", "EndDate")

df <- df[ , -which(names(df) %in% columns_to_remove)] ## works as expected

df <- reorder_factor_levels(df, "Q1", "Other") 

df$q1_group <- ifelse(df$Q1 == "University/Research institution", "University/Research institution", "Other")

df <- df %>%
  mutate(Q1 = str_wrap(Q1, width = 20))

#relocate columns 
df <- df %>% 
  relocate(Q10_4, .before = Q8) %>% 
  relocate(Q10_5, .after = Q10_4) %>% 
  relocate(Q10_6, .after = Q10_5) %>% 
  relocate(income_group, .after = Q8) %>%
  relocate(metrics_section_answered, .after = income_group)  %>%
  relocate(questions_section_answered, .after = metrics_section_answered)%>%
  relocate(evaluation_section_answered, .after = questions_section_answered)%>%
  relocate(confidence_section_answered, .after = evaluation_section_answered)%>%
  relocate(barriers_section_answered, .after = confidence_section_answered) %>%
  relocate(Q3_national, .after = barriers_section_answered)%>%
  relocate(Q3_sub_national, .after = Q3_national)%>%
  relocate(Q3_field, .after = Q3_sub_national)%>%
  relocate(Q3_other, .after = Q3_field)

df$Q14_4 <- ifelse(df$Q14_4 == "Single number / Point estimate", "Point estimates", df$Q14_4)

sub_df <- df %>% filter(if_any(c(Q7_3, Q7_5, Q7_6), ~ !is.na(.)))

sub_df <- sub_df %>%
  filter(!is.na(sub_df$Q8))

#identifiable interview participants & remove those that can't be interviewed
df$identifiable <- ifelse(!is.na(df$Q10_6), 1, 0)
df_interviewees <- df %>% filter(!is.na(Q10_6))

write.xlsx(df_interviewees, file = "~/Library/CloudStorage/GoogleDrive-paula.christen@cema.africa/My Drive/Infectech/survey/data/processed/interview_participants_14Jan25.xlsx") 

df_qual_analysis <- df[,c('ResponseId',
                          'identifiable',
                          'Q8',
                          'income_group',
                          'metrics_section_answered',
                          'questions_section_answered',
                          'evaluation_section_answered',
                          'confidence_section_answered',
                          'barriers_section_answered',
                          'Q3_national',
                          'Q3_sub_national',
                          'Q3_field',
                          'Q3_other',
                          'Q1',
                          'q1_group',
                          'Q17#1_1_1',
                          'Q17#1_2_1',
                          'Q17#1_3_1',
                          'Q17#1_4_1',
                          'Q17#1_5_1',
                          'Q19',
                          'Q21',
                          'Q23')]

# Identify columns with qual info
cols_to_check <- which(names(df_qual_analysis) == "Q17#1_1_1"):which(names(df_qual_analysis) == "Q23")

# Remove rows with all NAs in the specified columns
df_filtered <- df_qual_analysis[!apply(df_qual_analysis[, cols_to_check], 1, function(row) all(is.na(row))), ]

df <- df %>%
  filter(!is.na(df$ResponseId))

```

Survival curve to show dropout

Distribution of study participants

```{r echo=FALSE}
Q1_df <- df %>%
  filter(!is.na(df$StartDate)) %>%
  dplyr::filter(!is.na(Q1)) %>%
  dplyr::group_by(q1_group) %>%
  dplyr::summarise(Frequency = n()) %>%
  dplyr::mutate(Percent = round(Frequency/sum(Frequency)*100, 1)) 

Q1_df_sum <- Q1_df %>%
  dplyr::arrange(desc(q1_group)) %>%
  dplyr::mutate(Position = round((cumsum(Percent)- 0.5*Percent),0))

#Overview of study participants in survey
Q1_df <- df %>%
  filter(!is.na(df$StartDate)) %>%
  dplyr::filter(!is.na(Q1)) %>%
  dplyr::group_by(Q1) %>%
  dplyr::summarise(Frequency = n()) %>%
  dplyr::mutate(Percent = round(Frequency/sum(Frequency)*100, 1)) 

# Create a contingency table
tab <- table(df$Q1, df$income_group)

# Calculate row-wise percentages
tab_percent <- prop.table(tab, margin = 1) * 100

# Combine counts and percentages into a single table
formatted_table <- matrix(
  paste0(tab, " (", sprintf("%.1f", tab_percent), "%)"),
  nrow = nrow(tab),
  dimnames = dimnames(tab)
)

# Print as a data frame for nicer formatting
table <- as.data.frame.matrix(formatted_table)
table$org <- row.names(table)
```


```{r include=FALSE}

# Q3 - who they engaged with
national <- summarise_freq_percent(df, Q3_national)
subnational <- summarise_freq_percent(df, Q3_sub_national)
field <- summarise_freq_percent(df, Q3_field)

# Q7 - geographic scope of work
global <- summarise_freq_percent(df, Q7_1)
regional <- summarise_freq_percent(df, Q7_2)
national_scope <- summarise_freq_percent(df, Q7_3)
sub_national <- summarise_freq_percent(df, Q7_5)
field_scope <- summarise_freq_percent(df, Q7_6)

# Derived variable: engaged at national/subnational/field level
df$field_national_sn <- ifelse(!is.na(df$Q7_3) | 
                               !is.na(df$Q7_5) | 
                               !is.na(df$Q7_6), 1, 0)

# Summary of field_national_sn
field_national_sn_summary <- summarise_freq_percent(df, field_national_sn)


```


Which metrics were communicated?

```{r echo=FALSE}
communicated_how_region <- summarize_columns_no_grouping_count(
  df = df, 
  summary_cols = c("Q16_1", "Q16_2", "Q16_3", "Q16_6", "Q16_7", "Q16_8", "Q16_9", "Q16_10", "Q16_11", "Q16_12", "Q16_13", "Q16_14")
)

names(communicated_how_region) <- gsub("\\(.*?\\)|\\[.*?\\]", "", names(communicated_how_region))
names(communicated_how_region) <- gsub("\\s$", "", names(communicated_how_region)) 
names(communicated_how_region) <- gsub("\\)$", "", names(communicated_how_region))

# Reshape the data from wide to long format
df_long <- communicated_how_region %>% 
  pivot_longer(cols = c(2:13),
               names_to = "way_of_communication",
               values_to = "count") 

df_long <- df_long %>%
  mutate(way_of_communication = str_wrap(way_of_communication, width = 20))

df_long
```

Communicated how

```{r echo=FALSE}

communicated_how_region <- summarize_columns_count(
  df = df,
  group_col = "income_group", 
  summary_cols = c("Q16_1", "Q16_2", "Q16_3", "Q16_6", 
                   "Q16_7", "Q16_8", "Q16_9", "Q16_10", 
                   "Q16_11", "Q16_12", "Q16_13", "Q16_14"), 
  section = "metrics_section_answered")

names(communicated_how_region) <- gsub("\\(.*?\\)|\\[.*?\\]", "", names(communicated_how_region))
names(communicated_how_region) <- gsub("\\s$", "", names(communicated_how_region)) 
names(communicated_how_region) <- gsub("\\)$", "", names(communicated_how_region))

# Reshape the data from wide to long format
df_long <- communicated_how_region %>% 
  pivot_longer(cols = c(3:14),
               names_to = "way_of_communication",
               values_to = "count") %>%
  group_by(income_group) %>%
  mutate(proportion = count / n) %>%
  ungroup()

df_long <- df_long %>%
  mutate(way_of_communication = str_wrap(way_of_communication, width = 20))

# Order the phases by mean proportion in descending order
phase_order <- df_long %>%
  arrange(desc(proportion)) %>% 
  pull(way_of_communication)

df_long

```

Most policy relevant questions

```{r echo=FALSE}

# Create an empty data frame to store the results
df_matrix_no_grouping <- data.frame()

# Loop through each question from Q18_1 to Q18_12
for (i in 1:12) {
  # Construct the column names for the current question
  col_names <- paste0("Q18_", i, "_", c(1, 2, 3, 4, 6))
  
  Q18_prop <- summarize_columns_no_grouping_count(
      df = df,
      summary_cols = col_names)
    
  # Add a column for the Q18 question number
  Q18_prop$Q18_number <- i
    
  # Append the results to df_matrix
  df_matrix_no_grouping <- rbind(df_matrix_no_grouping, Q18_prop)
}

df_matrix_no_grouping$Q18_category <- ifelse(df_matrix_no_grouping$Q18_number %in% c(1,2,12), 
                                      "Non-Pharmaceutical Interventions and their Impact",
                                             ifelse(df_matrix_no_grouping$Q18_number %in% c(4,5,6,7), 
                                                    "Epidemic Projections and Modeling",
                                                    ifelse(df_matrix_no_grouping$Q18_number %in% c(3), 
                                                           "Herd Immunity and Reopening Strategies",
                                                           ifelse(df_matrix_no_grouping$Q18_number == 11, 
                                                                  "Healthcare Resource Allocation",
                                                                  ifelse(df_matrix_no_grouping$Q18_number %in% c(9,10), 
                                                                         "Vaccination Strategies",
                                                                         ifelse(df_matrix_no_grouping$Q18_number == 8, 
                                                                                "Economic Impact", 
                                                                                "Other"))))))

df_matrix_no_grouping$Q18_number <- ifelse(df_matrix_no_grouping$Q18_number == 1, 
                   "What is the effectiveness of different types of Non-pharmaceutical interventions? What are the potential outcomes of implementing restrictions at different time points?",
                   ifelse(df_matrix_no_grouping$Q18_number == 2,
                          "What are the potential outcomes of lifting restrictions at different points in time?",
                          ifelse(df_matrix_no_grouping$Q18_number == 3,
                                 "What is the projected timeline for achieving herd immunity? At what level of herd immunity can we safely reopen schools?",
                                 ifelse(df_matrix_no_grouping$Q18_number == 4,
                                        "What is the projected number of cases and deaths over the next x months?",
                                        ifelse(df_matrix_no_grouping$Q18_number == 5,
                                               "When is the peak of the epidemic expected to occur?",
                                               ifelse(df_matrix_no_grouping$Q18_number == 6,
                                                      "What is the expected duration of the epidemic wave?",
                                                      ifelse(df_matrix_no_grouping$Q18_number == 7,
                                                             "How do forecasted infection rates vary across different regions or cities?",
                                                             ifelse(df_matrix_no_grouping$Q18_number == 8,
                                                                    "What are the economic impacts of prolonged lockdowns on local businesses?",
                                                                    ifelse(df_matrix_no_grouping$Q18_number == 9,
                                                                           "What is the most effective strategy for prioritizing vaccine distribution?",
                                                                           ifelse(df_matrix_no_grouping$Q18_number == 10,
                                                                                  "How many vaccines do we need in the country/state/province?",
                                                                                  ifelse(df_matrix_no_grouping$Q18_number == 11,
                                                                                         "How many ventilators, hospital and ICU beds does each hospital need and when?",
                                                                                         "How will changes in public behavior impact the course of the epidemic?")))))))))))


questions_counts <- df %>%
  filter(questions_section_answered == 1)

denominator <- nrow(questions_counts)

df_matrix_no_grouping$n <- denominator

#The three most commonly asked questions are:
top_q <- df_matrix_no_grouping %>%
    top_n(3, n)

top_q$Q18_number

```

Most policy relevant questions by phase 

```{r echo=FALSE}
# Reshape the data from wide to long format
df_long <- df_matrix_no_grouping %>% 
  pivot_longer(cols = c("Discovery", "Escalation", "Acceleration", "Deceleration", "Preparation"), 
               names_to = "phase", 
               values_to = "count")

#The three most commonly asked questions are:
top_q <- df_long %>%
  group_by(phase) %>%
  top_n(1, count)

by_phase <- top_q[,c("phase","Q18_category", "Q18_number")]

by_phase
```

```{r}

df_long <- df_long %>%
  mutate(proportion = count / n)

# Summarize by category and phase
heatmap_data <- df_long %>%
  group_by(Q18_category, phase) %>%
  summarise(total_prop = mean(proportion), .groups = "drop")

# Optional: set order of phases
heatmap_data$phase <- factor(
  heatmap_data$phase,
  levels = c("Discovery", "Escalation", "Acceleration", "Deceleration", "Preparation")
)

# Step 1: Calculate proportions
df_long <- df_long %>%
  mutate(proportion = count / n)

df_long <- df_matrix_no_grouping %>% 
  pivot_longer(cols = c("Discovery", "Escalation", "Acceleration", "Deceleration", "Preparation"),
               names_to = "phase",
               values_to = "proportion")

```

Questions posed by income group

```{r echo=FALSE}
# Define the grouping columns
group_col <- "income_group"

# Create an empty data frame to store the results
df_matrix_region <- data.frame()

for (i in 1:12) {
  # Construct the column names for the current question
  col_names <- paste0("Q18_", i, "_", c(1, 2, 3, 4, 6))
  
  # Apply the summarize_columns2 function
  Q18_prop <- summarize_columns(
    df = df,
    group_col = group_col,
    summary_cols = col_names
  )
  
  # Remove "Missing" column if it exists
  if ("Missing" %in% names(Q18_prop)) {
    Q18_prop <- Q18_prop[, names(Q18_prop) != "Missing"]
  }
  
  # Add a column for the Q18 question number
  Q18_prop$Q18_number <- i
  
  # Append the result, safely handling differing column names
  df_matrix_region <- bind_rows(df_matrix_region, Q18_prop)
}

df_matrix_region$Q18_category <- ifelse(df_matrix_region$Q18_number %in% c(1,2,12), 
                                      "Non-Pharmaceutical Interventions and their Impact",
                                             ifelse(df_matrix_region$Q18_number %in% c(4,5,6,7), 
                                                    "Epidemic Projections and Modeling",
                                                    ifelse(df_matrix_region$Q18_number %in% c(3), 
                                                           "Herd Immunity and Reopening Strategies",
                                                           ifelse(df_matrix_region$Q18_number == 11, 
                                                                  "Healthcare Resource Allocation",
                                                                  ifelse(df_matrix_region$Q18_number %in% c(9,10), 
                                                                         "Vaccination Strategies",
                                                                         ifelse(df_matrix_region$Q18_number == 8, 
                                                                                "Economic Impact", 
                                                                                "Other"))))))


df_matrix_region$Q18_number <- ifelse(df_matrix_region$Q18_number == 1, 
                   "What is the effectiveness of different types of Non-pharmaceutical interventions? What are the potential outcomes of implementing restrictions at different time points?",
                   ifelse(df_matrix_region$Q18_number == 2,
                          "What are the potential outcomes of lifting restrictions at different points in time?",
                          ifelse(df_matrix_region$Q18_number == 3,
                                 "What is the projected timeline for achieving herd immunity? At what level of herd immunity can we safely reopen schools?",
                                 ifelse(df_matrix_region$Q18_number == 4,
                                        "What is the projected number of cases and deaths over the next x months?",
                                        ifelse(df_matrix_region$Q18_number == 5,
                                               "When is the peak of the epidemic expected to occur?",
                                               ifelse(df_matrix_region$Q18_number == 6,
                                                      "What is the expected duration of the epidemic wave?",
                                                      ifelse(df_matrix_region$Q18_number == 7,
                                                             "How do forecasted infection rates vary across different regions or cities?",
                                                             ifelse(df_matrix_region$Q18_number == 8,
                                                                    "What are the economic impacts of prolonged lockdowns on local businesses?",
                                                                    ifelse(df_matrix_region$Q18_number == 9,
                                                                           "What is the most effective strategy for prioritizing vaccine distribution?",
                                                                           ifelse(df_matrix_region$Q18_number == 10,
                                                                                  "How many vaccines do we need in the country/state/province?",
                                                                                  ifelse(df_matrix_region$Q18_number == 11,
                                                                                         "How many ventilators, hospital and ICU beds does each hospital need and when?",
                                                                                         "How will changes in public behavior impact the course of the epidemic?")))))))))))

df_matrix_region$total_vote_n <- df_matrix_region$Discovery + df_matrix_region$Escalation + df_matrix_region$Acceleration + df_matrix_region$Deceleration + df_matrix_region$Preparation

#The three most commonly asked questions are:
top_q <- df_matrix_region %>%
    group_by(income_group) %>%
    top_n(3, total_vote_n)

top_q
```


What are barriers to using evidence from epidemic forecasts?

```{r echo=FALSE}
Q25_prop_overall <- summarize_columns_no_grouping_count(
  df = df, 
  summary_cols = c("Q25_1", "Q25_10", "Q25_4", "Q25_11", "Q25_5","Q25_12", "Q25_2", "Q25_3", "Q25_7", "Q25_8", "Q25_9"))

# Reshape the data from wide to long format
df_long <- Q25_prop_overall %>% 
  pivot_longer(cols = c(2:12), 
               names_to = "format", 
               values_to = "proportion")

df_long <- df_long %>%
  mutate(phase = str_wrap(format, width = 40))

# Calculate the mean proportion for each phase
df_summary <- df_long %>% 
  group_by(phase) %>% 
  summarize(mean_prop = mean(proportion))

# Order the phases by mean proportion in descending order
phase_order <- df_summary %>% 
  arrange(desc(-mean_prop)) %>% 
  pull(phase)

```


What are barriers to using evidence from epidemic forecasts?

```{r echo=FALSE}

Q25_prop_overall <- summarize_columns_no_grouping_count(
  df = df, 
  summary_cols = c("Q25_1", "Q25_10", "Q25_4", "Q25_11", "Q25_5","Q25_12", "Q25_2", "Q25_3", "Q25_7", "Q25_8", "Q25_9"))

# Reshape the data from wide to long format
Q25_prop_overall %>% 
  pivot_longer(cols = c(2:12), 
               names_to = "format", 
               values_to = "proportion")
```

